services:
  db:
    image: postgres:15-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=reNews
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=reNews_db
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reNews -d reNews_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
